version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env


# version: '3.8'

# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: Dockerfile  # Pointing to your NGINX Dockerfile
#     ports:
#       - "80:80"
#     depends_on:
#       - backend

#   backend:
#     build:
#       context: ./backend
#     command: gunicorn wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     environment:
#       - DB_HOST=db
#       - DB_NAME=myprojectdb
#       - DB_USER=derek
#       - DB_PASSWORD=postgres
#       - DB_PORT=5432
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: myprojectdb
#       POSTGRES_USER: derek
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
